[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dept-starter-kit-template"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.30.0", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
axum = { version = "0.7.9", features = ["multipart", "macros"] }

node = { path = "../node" }
router = { path = "../router" }
helpers = { path = "../helpers" }
gateway = { path = "../gateway" }