[package]
name = "dept-starter-kit-template"
version = "0.1.0"
edition = "2021"

[dependencies]
iroh = { git = "https://github.com/n0-computer/iroh", rev = "v0.33.0" }
iroh-blobs = "0.33.1"
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1"
anyhow = "1"
tempfile = "3.19.1"
rand = "0.8.5"
