[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.9", features = ["multipart", "macros"] }
tower-http = { version = "0.6.2", features = ["cors"] }

api = { path = "../api" }
helpers = { path = "../helpers" }
